"use strict";

const nodeGlobals = {
  Buffer: "readonly",
  URL: "readonly",
  AbortController: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  console: "readonly",
  process: "readonly",
  require: "readonly",
  module: "readonly",
  __dirname: "readonly",
  __filename: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  structuredClone: "readonly",
  AbortSignal: "readonly",
  Headers: "readonly",
  fetch: "readonly",
  URLSearchParams: "readonly",
  window: "readonly",
  document: "readonly",
  location: "readonly",
  CSS: "readonly",
  Event: "readonly",
  HTMLElement: "readonly",
  HTMLFormElement: "readonly",
  requestAnimationFrame: "readonly",
  getComputedStyle: "readonly",
};

module.exports = [
  { ignores: ["node_modules/**", "dist/**", "data/**", "logs/**"] },
  {
    files: [
      "main.js",
      "preload.js",
      "lib/**/*.js",
      "scripts/**/*.js",
      "mock-portal/**/*.js",
      "tests/**/*.js",
    ],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "commonjs",
      globals: nodeGlobals,
    },
    rules: {
      "no-undef": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      eqeqeq: ["error", "always"],
      "no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      complexity: ["warn", 80],
    },
  },
  {
    files: ["renderer.js"],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        Node: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        Intl: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      eqeqeq: ["error", "always"],
      complexity: ["warn", 100],
    },
  },
];
